config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'flickr#index'
  get '/flickr', to: 'flickr#index', as: 'flickr'
  get '/flickr/search', to: 'flickr#search', as: 'search_flickr'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flickr_controller.rb
class FlickrController < ApplicationController

  def index
    render
  end

  def search
    @search_text = params["text"]

    if @search_text.present?
      @photos_data = flickr.photos.search(text: @search_text,
                                          sort: 'relevance',
                                          per_page: 10,
                                          extras: 'url_s')
    else
      flash[:error] = "Please enter correct search query"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flickr/_search_form.html.erb
<div class="ui input">
  <%= form_tag search_flickr_path, method: :get, id: "search_photos" do %>
    <%= text_field_tag :text, params[:text], { placeholder: "Search photos" } %>
    <%= submit_tag "Submit", class: "ui primary button" %>
  <% end %>
</div>

app/views/flickr/index.html.erb
<% if flash[:error].present? %>
  <%= render partial: "search_form" %>
<% end %>

<h2><i>Search excellent photos around the world here!</i></h2>

app/views/flickr/search.html.erb
<% if @photos_data.size.zero? %>
  No photos found for '<%= @search_text %>' :(
<% else %>
  <i>Results for '<%= @search_text %>'</i>
  <div class="ui relaxed horizontal list">
    <% @photos_data.each do |photo| %>
      <div class="item">
        <div class="content">
          <%= photo['title'] %>
        </div>
        <img src="<%= photo['url_s']%>" alt="<%= photo['title']%>" class="ui image">
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui inverted fixed menu">
      <div class="ui container">
        <%= link_to root_path, class: "item" do %>
          Flickr Example
        <% end %>
        <div class="right item">
          <%= render partial: "search_form" %>
        </div>
      </div>
    </div>
    <br />
    <div class="ui main container" style="margin-top:40px">
      <div class="ui fluid container">
        <% flash.each do |_, value| %>
        <div class="ui negative message">
          <i class="close icon"></i>
          <div class="header">
            <%= value %>
          </div>
        </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>